### ISSUE TITLE
I can't understand the training way

### ISSUE THREAD

**Issue by tanpengjie** [MediaBrain-SJTU/RegAD#11]
Dear author

From your paper and source code, it is known that the target category is chosen to be tested, and other categories in the datasets are used for training. I am extremely confused about it. In my opinion,  It should be that the target category is chosen to be tested, and all categories in the datasets are used for training. 

I will appreciate it if you can help me.

**Comment by chaoqinhuang** [comment]
This is exactly the setting of **few-shot** anomaly detection. This setting targets to evaluate the anomaly detection performance on an **unseen** category in order to test the **generalization ability** of the anomaly detection model. Thus, we should remove all the data of the target category from the training set, while only very few data of the target category are given in the support set during the test.
Of course, you can add all training data of the target category into both the training set and the support set. Higher performance will be gotten than the paper. But it is no longer few-shot anomaly detection but vanilla anomaly detection.

**Comment by tanpengjie** [comment]
Dear author

Thanks for your answer. In my view, it is an excellent idea, which has benefited me a lot. Hundreds of thanks. 
I have another doubt. The "Individual training" mentioned in the paper refers to that only samples of the target category are used for training,  and when the testing, only samples of the target category are tested?

**Comment by chaoqinhuang** [comment]
Yes but only the given few-shot data are used in the indivisual training.

**Comment by Nanala5** [comment]
Dear Author,
May I ask how the .pt file that supports_set is trained in detail? I see that what you share here is a pre-trained file, but there is no specific explanation.

**Comment by chaoqinhuang** [comment]
@Nanala5 The support set is a set of images. It is NOT a pre-trained file.

**Comment by wuyz0502** [comment]
Dear Author,
Sorry to bother you, I may be inaccurate in my expression, the support data set is indeed in the form of a group of. pt files, so I would like to ask how it is handled here.

**Comment by Nanala5** [comment]
> @Nanala5 The support set is a set of images. It is NOT a pre-trained file.

Dear Author,
Sorry to bother you, I may be inaccurate in my expression, the support data set is indeed in the form of a group of. pt files, so I would like to ask how it is handled here.

**Comment by Nanala5** [comment]
Dear Author,
Sorry to bother you, I may be inaccurate in my expression, the support data set is indeed in the form of a group of. pt files, so I would like to ask how it is handled here.

**Comment by Nanala5** [comment]
Dear Author,
Sorry to bother you, I may be inaccurate in my expression, the support data set is indeed in the form of a group of. pt files, so I would like to ask how it is handled here.

**Comment by chaoqinhuang** [comment]
> Dear Author, Sorry to bother you, I may be inaccurate in my expression, the support data set is indeed in the form of a group of. pt files, so I would like to ask how it is handled here.

Simply open the image data, transform them into tensors, and then save the tensors as a pt file. That's all. Please refer to #1 for the codes. Sorry, but I cannot understand "supports_set is trained" you mentioned before. It is an image support set for the few-shot testing, which contains the tensor-type images and needn't be trained.

**Comment by Nanala5** [comment]
> 
Dear Author,
Thank you very much for your answer.
