### ISSUE TITLE
How to understand the different formulas of STN in the two papers?

### ISSUE THREAD

**Issue by qiny1012** [MediaBrain-SJTU/RegAD#12]
In the paper “Spatial Transformer Networks”，the transformation formula of feature coordinates is as follows.
![image](https://user-images.githubusercontent.com/32615944/192485806-52319ab5-0208-4227-b18a-df31ef25292e.png)
$(x^t,y^t)$ in the back, $(x^s,y^s)$ in the front.
In the paper “Registration based Few-Shot Anomaly Detection”，the transformation formula of feature coordinates is as follows.
![image](https://user-images.githubusercontent.com/32615944/192486556-56f0af57-9901-48f6-b6b2-e60bcf22bd00.png)
$(x^t,y^t)$ in the front, $(x^s,y^s)$ in the back.

**Comment by Haoyan-Guan** [comment]
Thanks for pointing out this mistake. In code implementation, the STN is the same as the paper 'Spatial Transformer Networks'. In paper, the subscripts of the letters(s and t) are reversed.
