### ISSUE TITLE
Question about your training strategy.

### ISSUE THREAD

**Issue by FantasticGNU** [MediaBrain-SJTU/RegAD#17]
In your code, I noticeed that you do a test on the test set on every epoch, and save the best epoch. 
Maybe before finishing your training procedure, the test set shouldn't be seen?
It seems like that you decide the epoch number depend on the test set, I think it's not good.

**Comment by chaoqinhuang** [comment]
Thank you very much. To have a fair comparison with other baseline methods, we choose to follow their experimental setting and make sure the comparisons are fair.
