### ISSUE TITLE
关于训练自己数据集模型的问题

### ISSUE THREAD

**Issue by wangkaixiong** [MediaBrain-SJTU/RegAD#19]
作者，您好，首先看到您的论文的创新点很是惊艳，按照您开源的代码训练出自己数据集的模型，但在测试图像存在光照变换或尺寸变化时效果不佳，请问您在研究过程中是否碰到类似问题，如有的话，还希望能够分享下类似的心得，谢谢！

**Comment by chaoqinhuang** [comment]
感谢你对我们论文的关注，如果自己的数据有一些特殊的特点，建议可以针对性的采用一些数据增强
物体的尺寸变化我认为是有办法缓解的，比如说在测试前估计分布(normal distribution)的时候，加入改变物体的尺寸大小的数据增强扩充support set，这样normal distribution就能包含多种尺寸的统计分布，可能可以有比较好的效果
光照变化如果是那种整体的明暗变化，加一些brightness的数据增强可能有一些效果，如果是局部的一些阴影，个人感觉有可能会难一点

**Comment by wangkaixiong** [comment]
感谢作者及时准确的解惑，我明白了，谢谢

**Comment by EricLee0224** [comment]
> 感谢作者及时准确的解惑，我明白了，谢谢

Hi, 请问你们可以分享使用custom dataset生成support set文件的code吗？使用#1的方法写一直有报错（啊应该是我们个人原因导致）.. 如果可以的话，邮箱：liweize0224@gmail.com 万分感谢

**Comment by wangkaixiong** [comment]
作者，你好，我测试的时候发现单张图像带GPU运算需要14s，其中支撑样本计算多元高斯分布的时候数据量巨大，且测试图像计算马氏距离时数据量也比较大，请问论文中4.47s的适应时间是指哪部分时间呢，期待回复，谢谢
