### ISSUE TITLE
i met this error when i preparing data

### ISSUE THREAD

**Issue by wzr0108** [MediaBrain-SJTU/RegAD#2]
```
support_set/metal_nut/
support_set/metal_nut/8_10.pt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by wzr0108** [comment]
the dataset 'support_set.tar' is download from https://drive.google.com/file/d/1gUc-1WeoFTftMPNu8AmtvuD0NEqQoJG2/view?usp=sharing

**Comment by wzr0108** [comment]
i met a similar error when i unzip the checkpoint
```
save_checkpoints/rotation_scale/8/hazelnut/hazelnut_8_rotation_scale_model.pt
tar: Unexpected EOF in archive
tar: rmtlseek not stopped at a record boundary
tar: Error is not recoverable: exiting now
```

**Comment by chaoqinhuang** [comment]
Please use the following updated links:
For the checkpoints:
https://drive.google.com/file/d/1nEnM1xNIZXUrUIPTYf7t11ndTJhChV5h/view?usp=sharing
For the support sets:
https://drive.google.com/file/d/161zBrv_-E01M8AdzEG0IAI5hae5NUGvO/view?usp=sharing

**Comment by chaoqinhuang** [comment]
Please use the updated links:
For the support set
https://drive.google.com/file/d/161zBrv_-E01M8AdzEG0IAI5hae5NUGvO/view?usp=sharing
For the checkpoints
https://drive.google.com/file/d/1guZBh40btPRmxcnY_lud88V1NoT-eWWX/view?usp=sharing

**Comment by wzr0108** [comment]
thanks
