### ISSUE TITLE
SupportSet

### ISSUE THREAD

**Issue by Mason1992-Git** [MediaBrain-SJTU/RegAD#22]
Hi,dear author.
Can you provide a tutorial for supportset production？
thankyou

**Comment by chaoqinhuang** [comment]
Please refer to #1 for the codes.

**Comment by Mason1992-Git** [comment]
您好，您的来信已收到，我会尽快阅读并回信。谢谢。袁磊

**Comment by Mason1992-Git** [comment]
> Please refer to #1 for the codes.

thanks.
