### ISSUE TITLE
EOFError: Ran out of input on test.py

### ISSUE THREAD

**Issue by justbuyyal** [MediaBrain-SJTU/RegAD#24]
When I use test.py to test the pre-trained model with testing template command (python test.py --obj {} --shot {} --stn_mode rotation_scale) and I got an 'EOFError: Ran out of input' both on 'capsule' and 'grid' types.
I had tried 2, 4, 8 shot for testing and they all got the same EOFError.
Is there any fixed solutions ?

Thanks.

**Comment by chaoqinhuang** [comment]
This is because your downloaded support data is corrupted. Please download categories of capsule and grid on [Baidu Disk](https://pan.baidu.com/s/1fFwAB__bV0ja38B4w3JnXQ) (pll9) and [Baidu Disk](https://pan.baidu.com/s/1_--hXPPnlv3Tv7HHd4HRZQ) (ns0n)

**Comment by justbuyyal** [comment]
OK, thanks. It works.
