### ISSUE TITLE
关于复现代码的一些问题

### ISSUE THREAD

**Issue by yjnanan** [MediaBrain-SJTU/RegAD#25]
你好，我复习了你们的代码，在此我有三个问题想要请教一下：
1、在我复现训练代码的过程中，我发现在前几个epoch测试集的效果就已经达到了最后，后面几十个epoch的训练并没有在测试集上有提升，请问这是什么原因？训练截图如下：
![41672025010_ pic](https://user-images.githubusercontent.com/73676444/209495897-1fc69aa7-0c22-4ce9-a874-6c9229a9f00e.jpg)
2、为什么在测试的时候，是训练一个模型，测试10次，而不是训练10个模型，测试10次来得到平均结果，训练好一个模型难道做测试的时候结果还会不一样吗？
3、既然在训练的前几个epoch就已经达到了测试集上最好的效果，那么为什么要设置50个训练epoch呢？
期待得到你们的答复，谢谢！

**Comment by chaoqinhuang** [comment]
可以参考我在[#23 ](https://github.com/MediaBrain-SJTU/RegAD/issues/23)的回答，有些类别可能比较容易，可以提前stop training，比如你的这个例子，pixel-level已经
达到接近99%，当然可以不用训练50 epoch
测试10次，每次用的是不同的support data，所以结果会有不同。目的是测试模型在不同的support data下的performacne
