### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'cov'

### ISSUE THREAD

**Issue by dgl547437235** [MediaBrain-SJTU/RegAD#3]
hi,which torch version should i install, i try 1.12.0 and 1.8.0,but still casuse the problem

**Comment by chaoqinhuang** [comment]
Pytorch version should >=1.10.0 for torch.cov according to the official pytorch documentation.
https://pytorch.org/docs/1.12/generated/torch.cov.html?highlight=torch%20cov#torch.cov
Please double-check if your pytorch is well installed and if you run the correct pytorch version.

**Comment by wzr0108** [comment]
you can use this code  instead
```
tmp = np.cov(embedding_vectors[:, :, i].T.cpu().numpy())
cov[:, :, i] = torch.from_numpy(tmp).to(cov.device) + 0.01 * I
```
