### ISSUE TITLE
Visualization functions missing

### ISSUE THREAD

**Issue by SarthakGarg19** [MediaBrain-SJTU/RegAD#32]
Can you please help me with mark_boundaries() function Also roc_curve() and precision_recall_curve()

_Originally posted by @SarthakGarg19 in https://github.com/MediaBrain-SJTU/RegAD/issues/14#issuecomment-1452245823_

**Comment by chaoqinhuang** [comment]
import matplotlib
    import matplotlib.pyplot as plt
    from skimage import morphology
    from skimage.segmentation import mark_boundaries
    from sklearn.metrics import roc_auc_score, roc_curve, precision_recall_curve

**Comment by SarthakGarg19** [comment]
Thanks a lot!!
