### ISSUE TITLE
an issue about train and test

### ISSUE THREAD

**Issue by NAZABANMAAFK** [MediaBrain-SJTU/RegAD#33]
Thank you for your work! In your paper, you mentioned that we don't need to fine-tune or train for new classes. I don't understand how this is achieved. Does it mean that your pre-trained model can directly predict new classes? Also, what do you mean by "aggregated training" that you mentioned? In the code, if we want to train, we have to specify a certain class (obj), but I don't understand. I look forward to your reply!

**Comment by chaoqinhuang** [comment]
If you choose a specific class (obj) during training, all data from this class will be **excluded** from the training set (see Line-123 in mvtec.py). Then this model will be tested using this specific class during testing, to evaluate the performance encountering the new class. That is the only reason why we need to choose a specific class.

**Comment by NAZABANMAAFK** [comment]
Thanks very much for your response! I understand now!
