### ISSUE TITLE
关于文章方法思路的一些问题

### ISSUE THREAD

**Issue by zhoushijie28** [MediaBrain-SJTU/RegAD#35]
作者您好，最近在学习您文章方法时有一些小问题想向您请教：您的方法中使用配准的目的是否是将待测图片和支持集图片的物体作对齐呢，比如说把物体调整为相似的摆放角度和大小等，以方便后续做分布的估计？我刚刚接触这方面的知识，不知道理解的是否有偏差，期待您的解答

**Comment by chaoqinhuang** [comment]
Thank you for your attention. Your understanding is insightful. Welcome to connect us.
