### ISSUE TITLE
关于要下载的支持集问题

### ISSUE THREAD

**Issue by FourthM** [MediaBrain-SJTU/RegAD#37]
你好，你的代码中的测试集有为每个测试图片从训练集中挑选了8张图片，然后你最终的这个训练和测试都没有用到这个，而是提供了一个网上下载的支持集，我想知道这个支持集有什么不一样吗，也是随机选择的吗，谢谢！

**Comment by chaoqinhuang** [comment]
Please refer to #1 for the details of selecting the support set.
