### ISSUE TITLE
测试代码和论文不对应

### ISSUE THREAD

**Issue by flyinghu123** [MediaBrain-SJTU/RegAD#38]
论文`Inference`中提到是马氏距离得到score map后应用对应三个`inverse affine transformations`得到最终的score map，但是我在`test.py`中并没有看到对应的过程

**Comment by chaoqinhuang** [comment]
Please refer to Line 254-271 in stn.py. It does include the inverse affine transformations mentioned in the paper.

**Comment by flyinghu123** [comment]
你好，我仔细看了`stn.py`，代码描述的是将stn特征进行`inverse affine`， 然后`test.py`计算马氏距离模糊后得到的就是最终的score map， 而不是论文描述的马氏距离得到score后引用`inverse affine`得到最终score map。下方为论文inference部分截图: 
![image](https://github.com/MediaBrain-SJTU/RegAD/assets/48802940/00ab49fc-26af-4919-9921-e9b20d95eaff)

**Comment by chaoqinhuang** [comment]
Please pay attention to the "corresponding to the three STN modules" of the paper. 
The inverse transformation is conducted at the feature-level in the STN module, and then integrated into an abnormal score map. 
You should notice that the three STN modules correspond to different transformation matrices, as a result, the spaces are not aligned. If the inverse transformation is not conducted at the feature level, the features cannot be directly integrated as the features are not aligned.

**Comment by flyinghu123** [comment]
在`feature-level`应用`inverse affine`，那么是否意味着STN在inference阶段没有使用(因为STN会将特征进行`affine`然后`stn_output`又对特征进行了`inverse affine`，当然STN中的conv层还是使用了)，甚至还因为affine填充会带来多余噪声或者丢失部分特征
![image](https://github.com/MediaBrain-SJTU/RegAD/assets/48802940/b408e2e3-49af-4e00-a264-c65802346bb6)
![image](https://github.com/MediaBrain-SJTU/RegAD/assets/48802940/026e7498-30c9-411c-8e66-2364c8e9a493)

**Comment by chaoqinhuang** [comment]
I don't agree. You should notice that the input of STN2 is the feature transformed by STN1, without the use of the inverse transformations.

**Comment by chaoqinhuang** [comment]
BTW, please use English as part of our authors cannot read Chinese. It is my responsibility to make our discussion understood by all authors.

**Comment by flyinghu123** [comment]
Got it. Thank you. 
Does STN have the visualization result of image-level?

**Comment by chaoqinhuang** [comment]
Not yet, but you could try to visualize them.

**Comment by flyinghu123** [comment]
Okay, thank you!
