### ISSUE TITLE
不能运行python test.py --obj bottle --shot 2 --stn_mode rotation_scale

### ISSUE THREAD

**Issue by xqyd** [MediaBrain-SJTU/RegAD#4]
win11编程环境。

按照要求下载了所有tar文件，想办法将其解压（添加.gz后缀），所有的checkpoints预训练权重都是pca字样的（如bottle_2_pca_rotation_scale_model.pt），但是代码中是不带pca字样的，CKPT_name = f'./save_checkpoints/rotation_scale/{args.shot}/{args.obj}/{args.obj}_{args.shot}_rotation_scale_model.pt'，

故将其改为CKPT_name = f'./save_checkpoints/{args.shot}/{args.obj}/{args.obj}_{args.shot}_pca_rotation_scale_model.pt'之后，运行到STN.load_state_dict(model_CKPT['STN'])报错：
KeyError: 'STN'

请问如何解决，谢谢！

**Comment by chaoqinhuang** [comment]
Sorry but please use the updated links to download the correct checkpoints:
https://drive.google.com/file/d/1guZBh40btPRmxcnY_lud88V1NoT-eWWX/view?usp=sharing

**Comment by xqyd** [comment]
Thx! It works!
