### ISSUE TITLE
MPDD

### ISSUE THREAD

**Issue by JigSaw0331** [MediaBrain-SJTU/RegAD#7]
Where can I download the MPDD dataset? Thank you.

**Comment by chaoqinhuang** [comment]
Please visit the official website of MVTec with https://www.mvtec.com/company/research/datasets/mvtec-ad
or directly use this link
https://www.mydrive.ch/shares/38536/3830184030e49fe74747669442f0f282/download/420938113-1629952094/mvtec_anomaly_detection.tar.xz
to download the MVTec.

**Comment by chaoqinhuang** [comment]
Please use this link to download the MPDD dataset
https://vutbr-my.sharepoint.com/:f:/g/personal/xjezek16_vutbr_cz/EhHS_ufVigxDo3MC6Lweau0BVMuoCmhMZj6ddamiQ7-FnA?e=oHKCxI

**Comment by JigSaw0331** [comment]
Thx!
